sudo: required

language: python

python:
    - "3.6"

services:
    - docker

script:
    - make build
    - make test

after_success:
    - python -m pytest --cov=fbotics fbotics/tests/
    - codecov
