version: '3.3'

services:

  fbotics:
    image: aibotics/fbotics:newest
    command: tail -f /dev/null
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
